from names import *
from random import randint

name_instance = Names()
locales = [
    'ar_AA',
    'ar_EG',
    'ar_JO',
    'ar_PS',
    'ar_SA',
    'bg_BG',
    'bs_BA',
    'cs_CZ',
    'de_AT',
    'de_CH',
    'de_DE',
    'dk_DK',
    'el_GR',
    'en_AU',
    'en_CA',
    'en_GB',
    'en_IN',
    'en_NZ',
    'en_US',
    'es_ES',
    'es_MX',
    'et_EE',
    'fa_IR',
    'fi_FI',
    'fr_FR',
    'he_IL',
    'hr_HR',
    'hu_HU',
    'hy_AM',
    'id_ID',
    'it_IT',
    'ja_JP',
    'ka_GE',
    'ko_KR',
    'lt_LT',
    'lv_LV',
    'ne_NP',
    'nl_NL',
    'no_NO',
    'pl_PL',
    'pt_BR',
    'pt_PT',
    'ro_RO',
    'ru_RU',
    'sk_SK',
    'sl_SI',
    'sq_AL',
    'sr_Latn_RS',
    'sv_SE',
    'ta_IN',
    'th_TH',
    'tr_TR',
    'uk_UA',
    'zh_CN',
    'zh_TW'
]
local_int = randint(0, len(locales))
rand_local = locales[local_int]

print(name_instance.gen_name(rand_local))